import { AnimatePresence } from "framer-motion";

import "./globals.css";
import { Providers } from "./providers";
import Home from "./page";

// export const metadata = {
//   title: " || Ecomerce",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AnimatePresence mode="wait">
        <body className="bg-primary">
          <Providers>{children}</Providers>
        </body>
      </AnimatePresence>
    </html>
  );
}
